# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    # Windows Settings
    - resource: Microsoft.Windows.Developer/WindowsExplorer
      directives:
        description: Modify Explorer Settings
        allowPrerelease: true
      settings:
        FileExtensions: Show
        HiddenFiles: Show
        RestartExplorer: True
    # Features
    - resource: PSDscResources/WindowsOptionalFeature
      directives:
        description: Enable VirtualMachinePlatform
      settings:
        name: VirtualMachinePlatform
        ensure: Present
    - id: wslInstall
      resource: PSDscResources/WindowsOptionalFeature
      directives:
        description: Enable WSL
      settings:
        name: Microsoft-Windows-Subsystem-Linux
        ensure: Present
    - resource: PSDscResources/WindowsOptionalFeature
      directives:
        description: Enable HypervisorPlatform
      settings:
        name: HypervisorPlatform
        ensure: Present
    # Installs
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerShell
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Windows Terminal
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install DevHome
        allowPrerelease: true
      settings:
        id: Microsoft.DevHome
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install 7zip
        allowPrerelease: true
      settings:
        id: 7zip.7zip
        source: winget
    - id: vscodeInstall
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    # Add-ons
    - resource: PSDscResources/Script
      directives:
        description: Install VSCode Extensions
      dependsOn:
        - wslInstall
        - vscodeInstall
      settings:
        SetScript: |
          code --install-extension ms-vscode-remote.vscode-remote-extensionpack
          code --install-extension vscode-icons-team.vscode-icons
          code --install-extension VisualStudioExptTeam.vscodeintellicode
        GetScript: return $false
        TestScript: return $false