name: Build NuxtJS GitHub Pages

on:
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string
    # secrets: inherit

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v3

    - name: Set Workspace ENV_VAR
      id: set-wkdir
      run: |
        echo ::set-env name=OLD_PATH::"$GITHUB_WORKSPACE"
        echo ::set-env name=GITHUB_WORKSPACE::"$OLD_PATH/${{ inputs.app_dir }}"

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn export

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ inputs.app_dir }}/out
        force_orphan: true

    - name: Reset Workspace ENV_VAR
      id: reset-wkdir
      run: echo ::set-env name=GITHUB_WORKSPACE::"$OLD_PATH"